### ISSUE TITLE
Feature Improvement_01

### ISSUE THREAD

**Issue by yogareddy196** [ferrariofilippo/SaveApp_Kotlin#3]
### Description

I have observed that only some currency types are supported, I request that you please add more currency types for example, (Indian rupee - ₹ INR)

### Screenshots & Videos

![Screenshot_2024-06-09-14-45-19-00_f954f681efbc49e12aa4eba82126870b](https://github.com/ferrariofilippo/SaveApp_Kotlin/assets/85241646/509584d8-b1a0-4ce2-a6b5-484fd2d78524)

![Screenshot_2024-06-09-14-47-16-31_f954f681efbc49e12aa4eba82126870b](https://github.com/ferrariofilippo/SaveApp_Kotlin/assets/85241646/1acb47af-b78a-448b-ab96-1a3ff02b1abf)

### SaveApp Version

1.09

### Android Version

14

**Comment by ferrariofilippo** [comment]
Thank you for the report, I'll work on that

**Comment by ferrariofilippo** [comment]
This feature will be included in the next release, which will be available in the next few days
